# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["kailan@enviark.com"]
description = "A London Underground station guessing game"
language = "javascript"
manifest_version = 3
name = "tubeguessr"
service_id = "QYhKV5RGaqtsgNNMhtVre4"

[local_server]

[local_server.kv_stores]

[local_server.kv_stores.site-content]
file = "./static-publisher/kvstore.json"
format = "json"

[local_server.backends.mapbox]
url = "https://api.mapbox.com"

[scripts]
build = "npm run build"

[setup]

[setup.kv_stores]

[setup.kv_stores.site-content]
