/*
 * Generated by @fastly/compute-js-static-publish.
 */

// Commented items are defaults, feel free to modify and experiment!
// See README for a detailed explanation of the configuration options.

/** @type {import('@fastly/compute-js-static-publish').PublishContentConfig} */
const config = {
  rootDir: "../public",
  contentCompression: [ 'br', 'gzip' ],

  // Server settings are saved to the KV Store per collection
  server: {
    publicDirPrefix: "",
    staticItems: [],
    allowedEncodings: [ 'br', 'gzip' ],
    spaFile: false,
    notFoundPageFile: "/404.html",
    autoExt: [],
    autoIndex: ["index.html"],
  },
};

export default config;
